//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcBlog2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BLOG
    {
        public BLOG()
        {
            this.POSTs = new HashSet<POST>();
        }
    
        public int BLOG_ID { get; set; }
        public string BLOG_NOMBRE { get; set; }
    
        public virtual ICollection<POST> POSTs { get; set; }
    }
}
