//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcBlog2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMENTARIO
    {
        public int COM_ID { get; set; }
        public int POST_ID { get; set; }
        public Nullable<System.DateTime> COM_FECHA { get; set; }
        public string COM_NOMBREAUTOR { get; set; }
        public string COM_DETALLE { get; set; }
    
        public virtual POST POST { get; set; }
    }
}
